name: Frontend

on:
  push:
    branches:
      - main


permissions:
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Storage
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
              --source ./public \
              --destination '$web' \
              --auth-mode login \
              --overwrite

      - name: Purge Azure Front Door cache
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az afd endpoint purge --resource-group ${{ secrets.RESOURCE_GROUP }} --profile-name ${{ secrets.AFD_PROFILE_NAME }} --endpoint-name ${{ secrets.AFD_ENDPOINT_NAME }} --content-paths "/*"
